[package]
name = "treesitter"
version = "0.1.0"
edition = "2021"

[dependencies]
tree-sitter-rust = "0.23.0"
tree-sitter = "0.24.3"
serde_json = "1.0.132"
serde = { version = "1", features = ["derive"] }

[[bin]]
name = "try2"
path = "src/try2.rs"
